language: node_js
node_js:
  - "12"
services:
  - docker
before_install:
  - yarn
script:
  - yarn build
  # 记得在travis ci中配置工作室的docker hub 用户名和密码
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # 这里要把名字和项目名换一下
  - docker image build ./ -t 工作室仓库名字/项目名字:latest
  - docker image push 工作室仓库名字/项目名字:latest